### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by myton** [nmoutinho/stereo_calib_lib#1]
Hello, I get **"Aborted (core dumped)"** when run. 

**The following is log:**

**dH_dX.size: [1 x 0]**     **Prediction in EKFBase.cpp **
P_pred.size: [1 x 1]      **Prediction in EKFBase.cpp **
**R_explicit.size: [0 x 0]**  **Prediction in EKFBase.cpp **
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.2) ~/opencv/modules/core/src/matmul.cpp:1218: error: (-215:Assertion failed) type == (((6) & ((1 << 3) - 1)) + (((2)-1) << 3)) in function 'gemmImpl'.

**Output using gdb debug**:

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./main left.yaml right.yaml'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f757397d428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f757990c780 (LWP 26546))]
(gdb) bt
#0  0x00007f757397d428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f757397f02a in __GI_abort () at abort.c:89
#2  0x00007f75742c084d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f75742be6b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f75742be701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f75742be919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f75747b1a9a in cv::error(cv::Exception const&) () from /usr/local/lib/libopencv_core.so.3.4
#7  0x00007f75747b1b94 in cv::error(int, cv::String const&, char const*, char const*, int) () from /usr/local/lib/libopencv_core.so.3.4
#8  0x00007f75747bf909 in cv::errorNoReturn(int, cv::String const&, char const*, char const*, int) [clone .constprop.73] () from /usr/local/lib/libopencv_core.so.3.4
#9  0x00007f75747d29d0 in cv::gemmImpl(cv::Mat, cv::Mat, double, cv::Mat, double, cv::Mat, int) [clone .constprop.69] () from /usr/local/lib/libopencv_core.so.3.4
#10 0x00007f75747d7413 in void cv::callGemmImpl<double>(double const*, unsigned long, double const*, unsigned long, double, double const*, unsigned long, double, double*, unsigned long, int, int, int, int, int) () from /usr/local/lib/libopencv_core.so.3.4
#11 0x00007f75747d7ca7 in cv::hal::gemm64f(double const*, unsigned long, double const*, unsigned long, double, double const*, unsigned long, double, double*, unsigned long, int, int, int, int) ()
   from /usr/local/lib/libopencv_core.so.3.4
#12 0x00007f75747d922b in cv::gemm(cv::_InputArray const&, cv::_InputArray const&, double, cv::_InputArray const&, double, cv::_OutputArray const&, int) () from /usr/local/lib/libopencv_core.so.3.4
#13 0x00007f75748c6802 in cv::MatOp_GEMM::assign(cv::MatExpr const&, cv::Mat&, int) const () from /usr/local/lib/libopencv_core.so.3.4
#14 0x00007f75748da038 in cv::MatOp::matmul(cv::MatExpr const&, cv::MatExpr const&, cv::MatExpr&) const () from /usr/local/lib/libopencv_core.so.3.4
#15 0x00007f75748d9eff in cv::MatOp::matmul(cv::MatExpr const&, cv::MatExpr const&, cv::MatExpr&) const () from /usr/local/lib/libopencv_core.so.3.4
#16 0x00007f75748cea6d in cv::operator*(cv::MatExpr const&, cv::MatExpr const&) () from /usr/local/lib/libopencv_core.so.3.4
#17 0x0000000000428c4b in Prediction (X_k=..., U_k=..., P_k=..., Pn=..., Q=..., R_explicit=..., EKFb=..., X_pred=..., P_pred=..., Z_explicit_pred=..., dF_dX=..., dH_dX=..., dF_dU=..., S=...)
    at /home/zhangs/test/stereo_auto_calinration/stereo_calib_lib/src/filter/EKFBase.cpp:65
#18 0x0000000000424553 in EKF::Filter_Prediction (this=this@entry=0x7ffc8e8987a0) at /home/zhangs/test/stereo_auto_calinration/stereo_calib_lib/src/filter/EKF.cpp:12
#19 0x000000000041b3ff in spherical_multiple_filter_stereo_calib::calibrate (this=this@entry=0x7ffc8e898310, features_left=std::vector of length 7, capacity 7 = {...}, 
    features_right=std::vector of length 7, capacity 7 = {...}) at /home/zhangs/test/stereo_auto_calinration/stereo_calib_lib/src/spherical_multiple_filter_stereo_calib_lib.cpp:201
#20 0x000000000041e8ec in spherical_multiple_filter_stereo_calib::calibrate (this=this@entry=0x7ffc8e898310, image_left=..., image_right=...)
    at /home/zhangs/test/stereo_auto_calinration/stereo_calib_lib/src/spherical_multiple_filter_stereo_calib_lib.cpp:168
#21 0x000000000040765a in main (argc=<optimized out>, argv=<optimized out>) at /home/zhangs/test/stereo_auto_calinration/src/main.cc:169

**Error when calling `spherical_multiple_filter_stereo_calib::calibrate(std::vector<Feature> features_left, std::vector<Feature> features_right) function in  spherical_multiple_filter_stereo_calib_lib.cpp`**

**Comment by antithing** [comment]
Hi @myton I know this is old, but did you ever solve this? i am getting the same error using this lib. Thanks!
